/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q0ECUHLeSDa
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <Card className="mx-auto max-w-[350px]">
      <CardHeader>
        <CardTitle className="text-xl">AI-Powered Diet Generator</CardTitle>
        <CardDescription>Enter your information to generate a personalized diet plan</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="age">Age</Label>
            <Input id="age" placeholder="30" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="gender">Gender</Label>
            <Select defaultValue="male" id="gender">
              <option value="male">Male</option>
              <option value="female">Female</option>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="weight">Weight (kg)</Label>
            <Input id="weight" placeholder="70" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="height">Height (cm)</Label>
            <Input id="height" placeholder="170" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="activity-level">Activity Level</Label>
          <Select defaultValue="moderate" id="activity-level">
            <option value="sedentary">Sedentary</option>
            <option value="moderate">Moderate</option>
            <option value="active">Active</option>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="dietary-preferences">Dietary Preferences/Restrictions</Label>
          <Textarea id="dietary-preferences" placeholder="Enter your dietary preferences or restrictions" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="health-conditions">Health Conditions/Concerns</Label>
          <Textarea id="health-conditions" placeholder="Enter your health conditions or concerns" />
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto" onClick={undefined}>
          Generate Diet Plan
        </Button>
      </CardFooter>
    </Card>
  )
}
